version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: ./hasker_proj
    volumes:
      - ./hasker_proj:/opt/hasker_proj
      - static_volume:/opt/hasker_proj/staticfiles
      - media_volume:/opt/hasker_proj/media
    expose:
    - 8000
    env_file: .env
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
        - static_volume:/opt/hasker_proj/staticfiles
        - media_volume:/opt/hasker_proj/media
        - ./logs:/var/log/nginx
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: