version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    volumes:
      - .:/opt/hasker_proj
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: