# Generated by Django 2.2.4 on 2019-09-02 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='down_votes',
            field=models.ManyToManyField(blank=True, related_name='question_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='up_votes',
            field=models.ManyToManyField(blank=True, related_name='question_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
