# Generated by Django 2.2.4 on 2019-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0003_auto_20190903_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
